pkg/client/besu.go
pkg/client/besu_test.go
pkg/client/chain.go
pkg/client/contract.go
pkg/client/eth.go
pkg/client/proof.go
pkg/client/proof_test.go
pkg/contract/proof_test.go
pkg/testing/chains.go
tests/e2e/chains_test.go
tests/integration/contract_test.go

Besu client returns a tx receipt which includes revert reason when option `revert-reason-enabled` is enabled.

Add Besu client

---

contracts/core/IBFT2Client.sol

ibft2: fix path calculation

---

.github/workflows/test.yml
contracts/core/IBCChannel.sol
contracts/core/IBCConnection.sol
contracts/core/IBFT2Client.sol
contracts/core/IClient.sol
contracts/core/MockClient.sol

Fix to verifyPacketAcknowledgement receive the original data

---

contracts/core/IBCConnection.sol
pkg/testing/chains.go

Fix to verify a clientstate in connection handshake

---

contracts/core/IBCConnection.sol

Remove the unused assertions for consensus height

---

contracts/core/MockClient.sol

mockclient: add a comment

---

README.md
migrations/1_initial_migration.js
migrations/2_deploy_contracts.js
migrations/3_initialize_contract.js
pkg/testing/chains.go
pkg/testing/coordinator.go

Fix #51 (thanks to @toshihiko-okubo)

move contract initialization into truffle migrations

---

package.json

Signed-off-by: Masanori Yoshida <masanori.yoshida@datachain.jp>

add the postinstall npm script

---

README.md

Added a link to a tutorial web site using yui-ibc-solidity.
Signed-off-by: Ryo Sato <ryo.sato@datachain.jp>

add tutorial link

---

contracts/core/IBCHost.sol
contracts/core/IBCIdentifier.sol
pkg/contract/ibcidentifier/ibcidentifier.go

Add commitments packetReceipt and nextSequenceRecv

---

.github/workflows/test.yml
go.mod
go.sum

bump go version to v1.18

---

contracts/app/ICS20Transfer.sol
contracts/core/IBCHandler.sol
contracts/core/IBCModule.sol
tests/foundry/src/MockApp.sol

Add relayer address to IBC module

---

.github/workflows/test.yml

ci: remove unused patch

---

.github/workflows/test.yml
Makefile
contracts/app/ICS20Bank.sol
contracts/app/ICS20Transfer.sol
contracts/app/ICS20TransferBank.sol
contracts/app/SimpleToken.sol
contracts/core/IBCChannel.sol
contracts/core/IBCClient.sol
contracts/core/IBCConnection.sol
contracts/core/IBCHandler.sol
contracts/core/IBCHeight.sol
contracts/core/IBCHost.sol
contracts/core/IBCIdentifier.sol
contracts/core/IBCModule.sol
contracts/core/IBCMsgs.sol
contracts/core/IBFT2Client.sol
contracts/core/IClient.sol
contracts/core/MockClient.sol
foundry.toml

Introduce code formatting tool and check it on CI

---

Makefile

Signed-off-by: Masanori Yoshida <masanori.yoshida@datachain.jp>

Makefile: fix a small mistake

---

contracts/core/02-client/IBCClient.sol
contracts/core/03-connection/IBCConnection.sol
contracts/core/04-channel/IBCChannel.sol
contracts/core/24-host/IBCCommitment.sol
contracts/core/24-host/IBCStore.sol

Use openzeppelin's Strings.sol

---

Makefile
contracts/clients/IBFT2Client.sol
contracts/clients/MockClient.sol
contracts/core/02-client/ILightClient.sol

ics-02: Add verifyNonMembership support

---

pkg/relay/ethereum/chain.go
pkg/relay/ethereum/events.go

I actually ran into the #162  problem and fixed it.
This PR will search for packets below height and acknowledgement that are considered finalized.

Use finalized height to query packets

---

contracts/core/02-client/IBCClient.sol
contracts/core/03-connection/IBCConnection.sol
contracts/core/04-channel/IBCChannelHandshake.sol
contracts/core/04-channel/IBCPacket.sol
contracts/core/24-host/IBCStore.sol
contracts/core/25-handler/IBCQuerier.sol
tests/foundry/src/IBC.t.sol

Disallow STATE_TRY_OPEN as previous state in `connectionOpenAck`

---

contracts/core/04-channel/IBCChannelHandshake.sol

Fix channel handshake

---

.github/workflows/test.yml
.solhint.json
Makefile
contracts/apps/20-transfer/ICS20Transfer.sol
contracts/clients/IBFT2Client.sol
contracts/core/03-connection/IBCConnection.sol
contracts/core/04-channel/IBCChannelHandshake.sol
package-lock.json
package.json
tests/foundry/src/IBC.t.sol

Introduce solhint

---

chains/docker-compose.yml

use a new repository(`trufflesuite/ganache`) and update version to v7.8.0

Update ganache version

---

Makefile
package-lock.json
package.json
truffle-config.js

ref. https://github.com/hamdiallam/Solidity-RLP/issues/24

update solidity-rlp and compiler versions

---

contracts/core/04-channel/IBCChannelPacketTimeout.sol

ref.
- https://github.com/cosmos/ibc/blob/47fea20d4d400e967721396092c6b43398c65d78/spec/core/ics-004-channel-and-packet-semantics/README.md?plain=1#L1170
- https://github.com/cosmos/ibc/blob/main/spec/core/ics-004-channel-and-packet-semantics/README.md?plain=1#L1347

IBC-7: fix to remove state check in `timeoutPacket()` and `timeoutOnClose()`
